# Generated by Django 2.0 on 2018-05-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('filepath', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lat', models.FloatField(default=34.75)),
                ('lng', models.FloatField(default=135.5)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=8)),
            ],
        ),
    ]
